# Generated by Django 4.1.3 on 2023-01-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=110, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('gender', models.CharField(default=None, max_length=1)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(default=None, max_length=150)),
                ('city', models.CharField(default=None, max_length=80)),
                ('state', models.CharField(default=None, max_length=80)),
                ('country', models.CharField(default=None, max_length=80)),
                ('proff_id', models.CharField(default=None, max_length=80)),
                ('language', models.CharField(default=None, max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to='photos/profile_pics')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
