# Generated by Django 4.1.3 on 2023-01-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='proff_id',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=80),
        ),
    ]
